name: Build on Noetic
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        rosdistro: [noetic]
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-core
    steps:
    - name: Install apt dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive && sudo apt-get update
        sudo apt-get install -y build-essential clang-format-10 file git python3-catkin-lint python3-catkin-tools python3-pip python3-rosdep
        sudo apt install -y ros-${ROS_DISTRO}-octomap* ros-${ROS_DISTRO}-mavros* ros-${ROS_DISTRO}-vision-msgs
    - name: Use rosdep to install remaining dependencies
      run: |
        sudo rosdep init
        rosdep update
        rosdep install --from-paths src -i -y --rosdistro ${{ matrix.rosdistro }}
    - name: Build
      run: |
        . /opt/ros/${{ matrix.rosdistro }}/setup.sh
        catkin_make
