name: Ubuntu18.04 Melodic

on: 
  push: 
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'


jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"
      ROS_DISTRO: melodic
    steps:
      - name: Update Git
        run: |
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install git -y
      - uses: actions/checkout@v2
        with:
          submodule: recursive
      - name: Install ROS Melodic
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
          sudo apt install curl
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt update
          sudo apt install ros-melodic-desktop-full
          source /opt/ros/${ROS_DISTRO}/setup.bash
      - name: Install ROS packages with rosdep
        run: |
          sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
          sudo apt install python-rosdep
          sudo rosdep init
          rosdep update
      - name: Install dependencies
        run: |
          sudo apt install -y ros-${ROS_DISTRO}-octomap* ros-${ROS_DISTRO}-mavros* ros-${ROS_DISTRO}-vision-msgs

      - name: catkin make
        run: |
          mkdir -p ~/catkin_ws/src
          ln -s $GITHUB_WORKSPACE ~/catkin_ws/src/
          cd ~/catkin_ws
          source /opt/ros/${ROS_DISTRO}/setup.bash
          catkin_make
